#!/usr/bin/env python3
# the app gets Tokyo weather information.
import requests

url = 'http://weather.livedoor.com/forecast/webservice/json/v1?city=130010'
payload = {'city': '130010'}
data = requests.get(url, params=payload).json()

print(data['description']['text'])
